import csv, re

# SRC = digimon_status dump (extract with MbeDumper from gamedata/app_0.dx11.mvgl). COMPAT/OUT are in-repo.
_REPO = r"E:\ReverseEngineProjects\TimeStranger\DSTS-PlayerModelSwap"
SRC = r"E:\ReverseEngineProjects\TimeStranger\dump\digimon_status.digimon_status_data.csv"
COMPAT = _REPO + r"\data\PLAYER_ANIM_COMPATIBILITY.csv"
OUT = _REPO + r"\src\PlayerModelSwap\Digimon.g.cs"

def pretty(char_name):
    n = char_name[5:] if char_name.startswith("char_") else char_name
    parts = n.replace("_", " ").split(" ")
    return "".join("".join(seg.capitalize() for seg in p.split("-")) for p in parts if p)

# id -> humanoid role count
roles = {}
with open(COMPAT, encoding="utf-8", newline="") as f:
    for r in csv.DictReader(f):
        roles[int(r["id"])] = int(r["roles"])

def grade(cid):
    if cid not in roles: return ("U", 5)      # unrated (no skeleton found)
    n = roles[cid]
    if n >= 15: return ("A", 0)
    if n >= 12: return ("B", 1)
    if n >= 9:  return ("C", 2)
    if n >= 5:  return ("D", 3)
    return ("F", 4)

rows = []
with open(SRC, encoding="utf-8", newline="") as f:
    r = csv.reader(f); next(r)
    for rec in r:
        if len(rec) < 4: continue
        rid, name, code = rec[0].strip(), rec[2].strip(), rec[3].strip()
        if not rid.isdigit() or not name.startswith("char_") or not re.fullmatch(r"chr\d{3,}", code): continue
        rows.append((int(rid), name, code))
rows = sorted({i: (i, n, c) for i, n, c in rows}.values())

# build members: name = <Grade>_<Ident>, ordered by (grade rank, ident)
seen = set(); members = []
for i, name, code in rows:
    g, rank = grade(i)
    ident = pretty(name)
    if not ident or ident[0].isdigit(): ident = "D" + ident
    full = f"{g}_{ident}"
    if full in seen: full = f"{g}_{ident}_{i}"
    seen.add(full)
    members.append((rank, full, i, code))
members.sort(key=lambda m: (m[0], m[1]))

L = []
L.append("// AUTO-GENERATED by scratchpad/gen_cs2.py. Do not edit by hand.")
L.append("// Name prefix = player-animation compatibility tier (from skeleton bone-role analysis):")
L.append("//   A = Excellent (full humanoid rig)   B = Good   C = Partial   D = Poor")
L.append("//   F = Incompatible (non-humanoid; will T-pose)   U = Unrated (no skeleton data)")
L.append("using System.Collections.Generic;")
L.append("")
L.append("namespace TimeStranger.PlayerModelSwap;")
L.append("")
L.append("/// <summary>Player Digimon choices. Enum value = in-game Digimon id. Name prefix = compat tier.</summary>")
L.append("public enum PlayerDigimon")
L.append("{")
L.append("    None = 0,")
for rank, full, i, code in members:
    L.append(f"    {full} = {i},")
L.append("}")
L.append("")
L.append("public static class DigimonModels")
L.append("{")
L.append("    public static readonly Dictionary<int, string> Codes = new()")
L.append("    {")
for rank, full, i, code in sorted(members, key=lambda m: m[2]):
    L.append(f'        {{ {i}, "{code}" }},')
L.append("    };")
L.append("}")

open(OUT, "w", encoding="utf-8", newline="\r\n").write("\n".join(L) + "\n")

from collections import Counter
c = Counter(g for _, full, i, _ in members for g in [full.split("_")[0]])
print("members:", len(members), "| tier counts:", dict(c))
print("sample A:", [m[1] for m in members if m[1].startswith("A_")][:3])
print("sample F:", [m[1] for m in members if m[1].startswith("F_")][:3])
print("Agumon ->", [m[1] for m in members if "Agumon" in m[1] and m[3]=="chr050"])
